### ISSUE TITLE
Fallo al mostrar los eventos

### ISSUE THREAD

**Issue by Jogua** [fblupi/grado_informatica-MDA#10]
Esto es cuando se muestra la lista (index.php)
![evento](https://cloud.githubusercontent.com/assets/11507971/11784452/a28c1510-a27c-11e5-8f48-3ea6e3c85052.JPG)

**Comment by louri91** [comment]
Eso está arreglado desde el viernes pasado :( ¿por qué no se te ve bien?

**Comment by louri91** [comment]
![captura de pantalla 2015-12-15 a las 9 53 31](https://cloud.githubusercontent.com/assets/9786318/11806205/beaf2706-a311-11e5-846a-d55cf3e9bd75.png)

**Comment by Jogua** [comment]
Perfecto!! Seria un error de sincronización
